### ISSUE TITLE
More buttonz

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ShyykoSerhiy/vscode-spotify#1]
![image](https://cloud.githubusercontent.com/assets/159209/11413109/2acdd810-939a-11e5-97eb-ddb8d875bd0b.png)

Start/stop is pretty nice but having prev next here would be just awesome, it's basically unused space.

Thanks for the plugin btw it's really cool.

**Comment by bpasero** [comment]
Love this plugin!!!! Please please allow me to skip to the next song :)

**Comment by ShyykoSerhiy** [comment]
Coming in 0.0.3.:)

**Comment by ShyykoSerhiy** [comment]
Implemented in 0.0.3.
So now we have 3 ways to skip to the next song:
1. Commands palette
![commandspalette](https://cloud.githubusercontent.com/assets/1106995/11446108/6d50d118-953b-11e5-85cb-b134ffd5061a.gif)
2. Hotkey
![hotkey](https://cloud.githubusercontent.com/assets/1106995/11446110/726a3d7e-953b-11e5-9d39-b41cc45069e1.gif)
3. Button
![buttons](https://cloud.githubusercontent.com/assets/1106995/11446112/7969fa6a-953b-11e5-84f3-aa0254e34c84.gif)
The more the merrier!:sparkles:

**Comment by bpasero** [comment]
@ShyykoSerhiy ahaha, works epic. kudos :)
