### ISSUE TITLE
vscode-spotify in Remote Mode

### ISSUE THREAD

**Issue by tvvignesh** [ShyykoSerhiy/vscode-spotify#101]
Noticed that vscode-spotify authentication fails when used in remote ssh mode (localhost redirection fails) - https://code.visualstudio.com/docs/remote/ssh

It may need to be disabled in remote mode.

**Comment by jlfsjunior** [comment]
Any workarounds for this issue? I work mainly on remote and I really find this extension useful...

**Comment by ShyykoSerhiy** [comment]
I'm working on workaround for remote mode. It should be released around this weekend. It's a quite big release so no guaranties yet.

**Comment by wrussell1999** [comment]
Remote mode also doesn't work properly for WSL. I imagine this is because it runs on the host side, rather than the UI side. Not particularly easy, if at all possible, to move to UI I imagine

**Comment by roblourens** [comment]
This extension can run as a UI extension. You can declare this in the package.json with `extensionKind`. User-side workaround, set

```
"remote.extensionKind": {
    "shyykoserhiy.vscode-spotify": "ui"
},
```

**Comment by fredbaa** [comment]
has the workaround been released?

**Comment by Mert-Ergin** [comment]
> This extension can run as a UI extension. You can declare this in the package.json with `extensionKind`. User-side workaround, set
> 
> ```
> "remote.extensionKind": {
>     "shyykoserhiy.vscode-spotify": "ui"
> },
> ```

This works. Added following line in package.json on my local. (under C:\Users\{USERNAME}\.vscode\extensions\shyykoserhiy.vscode-spotify-3.1.0 for windows.)
```
	"extensionKind": [
		"ui"
	],

```
You also have to delete the extension from your remote to make it work.

**Comment by tvvignesh** [comment]
I have not tested it (moved out of spotify back to youtube :smiley:  ). But since it has been confirmed that it works, closing this issue.
