### ISSUE TITLE
pop-up tab "Music Time Dashboard"

### ISSUE THREAD

**Issue by rmb-dev** [ShyykoSerhiy/vscode-spotify#108]
After deleting an extension I have this empty pop-up tab "Music Time Dashboard". How to get rid of it? 
![issue](https://user-images.githubusercontent.com/22654796/61566743-ce4c7400-aa85-11e9-99d3-6c8cdd219b6d.png)

**Comment by ShyykoSerhiy** [comment]
Hi, @rmb-dev , I think this is from https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode extension ( https://github.com/swdotcom/swdc-vscode ). It's not from vscode-spotify . Hope it helps.

**Comment by rmb-dev** [comment]
Yep, it is. Dunno why I have this pop-up tab only now.
Thanks
