### ISSUE TITLE
"Seek to position in currently playing track"

### ISSUE THREAD

**Issue by alexanderpalsson** [ShyykoSerhiy/vscode-spotify#119]
Is there any chance "Seek to position in currently playing track" will be implemented in further versions?

I love this extension, thank you so much!

**Comment by ShyykoSerhiy** [comment]
There is an api for that https://developer.spotify.com/documentation/web-api/reference/player/seek-to-position-in-currently-playing-track/ ,  so yes it's possible to do. In what way do you want this to be implemented, a vscode command with input for the time?

**Comment by alexanderpalsson** [comment]
Yes, I saw that one in the web-api! As I understood it needs a time input, so my thought was that implementing commands that skip for example 10 seconds, 30 seconds or a minute in the song would be cool. Then you can bind which of these preferable skipping times yourself.

**Comment by ShyykoSerhiy** [comment]
Released in 3.2.0
