### ISSUE TITLE
High CPU usage on MacOS

### ISSUE THREAD

**Issue by roblourens** [ShyykoSerhiy/vscode-spotify#12]
I filed this - https://github.com/Microsoft/vscode/issues/14685 - , then realized it goes away when I disable this extension.

**Comment by ShyykoSerhiy** [comment]
I'll look into this. Thx

**Comment by ShyykoSerhiy** [comment]
https://developer.spotify.com/applescript-api/ is responsible for high cpu usage.

partially 'fixed' by adding bigger interval query interval. Might be more optimized if https://github.com/Microsoft/vscode/issues/18263 implemented. Maybe I'll have a look at https://github.com/Microsoft/vscode/issues/18263 myself. 

Also It might be good idea to add a way in config to switch from applescript to querying spotify's local web server (the same way vscode-spotify works on windows)

**Comment by ShyykoSerhiy** [comment]
Fixed. Use spotify.useCombinedApproachOnMacOS: true.

**Comment by ShyykoSerhiy** [comment]
spotify.useCombinedApproachOnMacOS is now true by default from 2.2.0 version
