### ISSUE TITLE
how do you sign in?

### ISSUE THREAD

**Issue by Dan-Gamin** [ShyykoSerhiy/vscode-spotify#124]
after installing **vscode-spotify** I realized that I need to log in. then I discovered the ` Spotify sign in` command. I ran it, then I got this error:
`
Unable to open 'login': Unable to read file '\login' (Error: Unable to resolve non-existing file '\login').
`
it had a button called "create file", so I clicked on it. then I got this:
`
Unable to write file '\login' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'C:\login')
`

any ideas about fixing this?

**Comment by ShyykoSerhiy** [comment]
That's quite an interesting error and I have no idea what's happening here. I'm working on a new release that will add an ability to sign in manually if current semi-automated approach doesn't work for some reason. I expect to release a new version by the end of next week.

**Comment by Dan-Gamin** [comment]
Thanks 😀😃😄

**Comment by doonv** [comment]
This issue is now ancient. And it's cluttering up my other issues. I'm closing this.
