### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by hugolompto** [ShyykoSerhiy/vscode-spotify#132]
Hello,
When I want to skip music, I have this error : 
vscode-spotify: Failed to perform operation Unknown error: status code403 ; {
  "error" : {
    "status" : 403,
    "message" : "Player command failed: Premium required",
    "reason" : "PREMIUM_REQUIRED"
  }
}

**Comment by yordanzhelevdev** [comment]
Do you have a premium?

**Comment by hugolompto** [comment]
No

**Comment by yordanzhelevdev** [comment]
You can't skip without premium

**Comment by hugolompto** [comment]
Okay

**Comment by hugolompto** [comment]
You Can close if you want
