### ISSUE TITLE
Lyrics functionality doesn't work

### ISSUE THREAD

**Issue by yordanzhelevdev** [ShyykoSerhiy/vscode-spotify#133]
When I click on the icon to show the lyrics nothing happens

**Comment by miguelBinpar** [comment]
Same here.

Additional info:

- vscode-spotify: `v3.1.0`
- VS Code:
  - Version: `1.47.3`
  - Commit: `91899dcef7b8110878ea59626991a18c8a6a1b3e`
  - Date: 2020-07-23T13:08:29.692Z (5 days ago)
  - Electron: `7.3.2`
  - Chrome: `78.0.3904.130`
  - Node.js: `12.8.1`
  - V8: `7.8.279.23-electron.0`
  - OS: Darwin x64 18.6.0

**Comment by itsjoeoui** [comment]
Same here as well

**Comment by kirilinsky** [comment]
same problem

**Comment by nerdophile** [comment]
Same here

**Comment by HYPERDRIVE-Motivator** [comment]
I have the same problem as well

**Comment by guodong2005** [comment]
same here

**Comment by KotletJB** [comment]
same here

**Comment by ShyykoSerhiy** [comment]
Fix released in 3.2.0

**Comment by itsjoeoui** [comment]
> Fix released in 3.2.0

Thanks :)

**Comment by mplachter** [comment]
I know this says it was fixed but its not working in `v3.2.1`
