### ISSUE TITLE
How to enable status bar controls?

### ISSUE THREAD

**Issue by TheFern2** [ShyykoSerhiy/vscode-spotify#141]
I installed the extension on the following system:

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-51-generic (Ubuntu 20.04)
```
I can control spotify with commands just fine, but all I can see on the status bar is the signout button as shown below. 

![image](https://user-images.githubusercontent.com/10265682/97935194-79e20c00-1d3d-11eb-9e96-49c874c009cd.png)

**Comment by vilhelmprytz** [comment]
The same thing has happened to me, it used to show more information but now it doesn't.

**Comment by ShyykoSerhiy** [comment]
The only thing I can think of is that some other extension is takes to much space in the status bar so other controls don't have enough space to be visible. @TheFern2 can you please try setting up spotify.priorityBase to smth like 1000(this will make sure that vscode-spotify's controls have higher priority) to debug (you'll need to restart vscode completely after the change) and see if this fixes the issue?

**Comment by TheFern2** [comment]
@ShyykoSerhiy  Thanks for the help. I have a pretty huge monitor with tons of space too on the status bar, but I will debug a bit when I get home. I might turn off other extensions too just to make sure. Btw works perfect on Windows10, my home driver is Debian/Kubuntu 20.04.

**Comment by TheFern2** [comment]
> The same thing has happened to me, it used to show more information but now it doesn't.

What's your OS?

**Comment by TheFern2** [comment]
Putting 1000 on priority didn't help, still showing just the signout. I am not so sure the priority is the issue here. I opened up a folder with a few text files just to avoid activating any extensions. All you see is the signout way on the left corner.

![image](https://user-images.githubusercontent.com/10265682/98057160-3b188880-1e07-11eb-84a6-645b0aaad4d9.png)

If you want I can do live debug, if you have any breakpoints in mind. Send me the file and line and I can report back.

**Comment by TheFern2** [comment]
Would enable logs be helpful here? I see that on the config options. Where do the logs go to?
Lemme know if I can provide better details, I have the extension ready to debugging if needed to.

**Comment by fraser018** [comment]
I also have this issue, just installed the extension to give it a go.
I'm on Linux (Manjaro) however I am using spotifyd instead of the the actual client. I do seem to be able to change songs in the side bar though so I believe it is connected correctly

**Comment by TheFern2** [comment]
@ShyykoSerhiy  I am thinking something is wrong with LinuxSpotifyClient class, at least that's my first thought. If I force web api usage, and restart vscode all the control buttons appear on the status bar.

```typescript
const platform = os.platform();
        if (isWebApiSpotifyClient()) {
            this.spotifyClient = new WebApiSpotifyClient(queryStatus);
            return this.spotifyClient;
        }

        if (platform === 'darwin') {
            this.spotifyClient = new OsxSpotifyClient(queryStatus);
        }
        if (platform === 'linux') {
            this.spotifyClient = new LinuxSpotifyClient(queryStatus);
        }

        return this.spotifyClient;
    }
```

@fraser018 can you try that? Enable Force Web Api Implementation, and restart vscode.

![image](https://user-images.githubusercontent.com/10265682/98313283-1b18ce80-1f99-11eb-99bc-dbc7450c565c.png)

**Comment by fraser018** [comment]
This seems to work but I had to have music already playing elsewhere. 
I used spotify-tui to start a song and then the icons displayed at the bottom of VS Code and I am able to control playback.

**Comment by TheFern2** [comment]
@fraser018 Thanks, at least we've narrowed it down to the Linux client class. Seems like is failing there, or perhaps an interface class, still don't know where exactly. I might put a breakpoint on each log output line. On the debug console there's a message saying output is too large to display. Which might tell us what's going on. 

I'll do a bit more debugging during the weekend.

**Comment by TheFern2** [comment]
Here's the rub. I can stop/play music from vscode to spotify app which means dbus commands are actually working properly. Just so I wasn't going crazy I went ahead and did the dbus commands from `linux-spotify-client.ts` in the terminal and they all seemed to work fine. So all vscode - spotify dbus communication is up and running as far as I can tell.

In `spotify-status.ts` line 27 I set a breakpoint, and the state pretty much looks like it not setting properly or something else is stopping it from setting, either way spotify is running, but the extension has the status as not running.

```typescript
render() {
        const state = getState();
        // Create as needed
        if (!this._statusBarItem) {
            this._statusBarItem = window.createStatusBarItem(StatusBarAlignment.Left, getButtonPriority('trackInfo'));
            this._statusBarItem.show();
        }
        if (!this._spotifyControls) {
            this._spotifyControls = new SpotifyControls();
            this._spotifyControls.showVisible();
        }
        if (this.loginState !== state.loginState) {
            this.loginState = state.loginState;
            this._spotifyControls.showHideAuthButtons();
        }

        if (state.isRunning) {
            const { state: playing, volume, isRepeating, isShuffling } = state.playerState;
            const text = this.formattedTrackInfo(state.track);
            let toRedraw = false;
...
```

![image](https://user-images.githubusercontent.com/10265682/98426607-16b6e900-205f-11eb-883b-c210c403a878.png)


If I negate the `isRunning` status as shown below line 42, and reload the buttons appear and work just fine. Having a bit of trouble finding when is the state supposed to be set in the store, or what's stopping it from having the current status.

```typescript
if (!state.isRunning) {
    const { state: playing, volume, isRepeating, isShuffling } = state.playerState;
...
```

Obviusly song name is not shown because that's also not retrieved or stored, but the buttons seem to work fine otherwise.
![image](https://user-images.githubusercontent.com/10265682/98426738-af4d6900-205f-11eb-909a-1302af08c8b3.png)

Running the dbus command the metadata in terminal everything is retrieved fine:

```
~ ❯❯❯ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata
method return time=1604709850.258668 sender=:1.27687 -> destination=:1.30311 serial=2284 reply_serial=2
   variant       array [
         dict entry(
            string "mpris:trackid"
            variant                string "spotify:track:3XkUCBouaD0NOAjfbi5D95"
         )
         dict entry(
            string "mpris:length"
            variant                uint64 185852000
         )
         dict entry(
            string "mpris:artUrl"
            variant                string "https://open.spotify.com/image/ab67616d00001e026a7b60bfd50501e8379f6558"
         )
         dict entry(
            string "xesam:album"
            variant                string "Stirring Child Spirits"
         )
         dict entry(
            string "xesam:albumArtist"
            variant                array [
                  string "Julien Mier"
               ]
         )
         dict entry(
            string "xesam:artist"
            variant                array [
                  string "Julien Mier"
               ]
         )
         dict entry(
            string "xesam:autoRating"
            variant                double 0.43
         )
         dict entry(
            string "xesam:discNumber"
            variant                int32 1
         )
         dict entry(
            string "xesam:title"
            variant                string "Jasmine Oceans"
         )
         dict entry(
            string "xesam:trackNumber"
            variant                int32 1
         )
         dict entry(
            string "xesam:url"
            variant                string "https://open.spotify.com/track/3XkUCBouaD0NOAjfbi5D95"
         )
      ]

```

I haven't done much with redux, but in `root-reducer.ts` `action.type=@@redux/INIT` which doesn't match any of the if statements.

![image](https://user-images.githubusercontent.com/10265682/98427159-a3fb3d00-2061-11eb-83c3-7e8816175f09.png)

**Comment by ShyykoSerhiy** [comment]
Fixed linux client implementation in 3.2.1. Thanks @TheFern2  for debugging the issue. Added you as a contributor in https://github.com/ShyykoSerhiy/vscode-spotify#contributing . Cheers

**Comment by TheFern2** [comment]
Nice glad to be able to contribute! I did see earlier today when I set a breakpoint on getStatus, how it was going to finally still even after retrieving the status, didn't look right. Dunno why it didn't caught my eyes then. Glad it is fixed. Thank you very much!

**Comment by TheFern2** [comment]
@vilhelmprytz @fraser018 make sure to checkout the lastest update.

Also @fraser018 your issue with spotifyd is documented here #140 I use official spotify app, so I don't see that problem.

**Comment by fraser018** [comment]
Cheers for that all, yeah working better on my end now. awesome!
