### ISSUE TITLE
Not Play the songs?

### ISSUE THREAD

**Issue by TeoDev1611** [ShyykoSerhiy/vscode-spotify#144]
vscode-spotify: Failed to perform operation Unknown error: status code403 ; { "error" : { "status" : 403, "message" : "Player command failed: Premium required", "reason" : "PREMIUM_REQUIRED" } }

This error :c 😢

**Comment by sharansharma94** [comment]
Are you using windows
This extension requires Spotify Premium to work on Windows

**Comment by TeoDev1611** [comment]
Yes i Use windows :c Thanks
