### ISSUE TITLE
Lyrics no longer loading

### ISSUE THREAD

**Issue by M1XZG** [ShyykoSerhiy/vscode-spotify#169]
I'm seeing a repeatable issue with this extension. 

Lyrics are no longer loading correctly. It's happening for every song I've recently tried. 

Examples:

`Red Hot Chili Peppers - Californication` loads only this on the first line. However manually editing the URL to Genius works in a browser
https://genius.com/Red-Hot-Chili-Peppers-Californication-lyrics

Another example: `Busted - Year 3000`
https://genius.com/Busted-year-3000-lyrics

I'm not sure how long this has been broken but it's possible `genius.com` has changed how they serve up lyrics?

**Comment by Lipatant** [comment]
I have the same problem.
