### ISSUE TITLE
Failed to initialize vscode-spotify. We'll keep trying every 20 seconds. (New VSCode Insiders / New Spotify ?)

### ISSUE THREAD

**Issue by iTouchTheSky** [ShyykoSerhiy/vscode-spotify#17]
I have the following message today following a VSCode Insiders update + had a Spotify update recently too.

I don't know what I can provide to help debugging, let me know and I should provide.

**Comment by ShyykoSerhiy** [comment]
@iTouchTheSky, it's probably connected to https://github.com/ShyykoSerhiy/spotilocal/pull/1. 
I'll try to reproduce the problem on my side.

**Comment by ShyykoSerhiy** [comment]
@iTouchTheSky, can you please send version of Spotify you are using (like 1.0.63.617.g5aca9a2a) ?

**Comment by iTouchTheSky** [comment]
@ShyykoSerhiy It's the same as you mentionned

**Comment by ShyykoSerhiy** [comment]
And you OS?

**Comment by iTouchTheSky** [comment]
Windows 10 Pro x64 V1703(15063.540)

**Comment by robertodurand** [comment]
VSCode is displaying the same message. Here are my specs:

Windows 10 Enterprise
Sportify: 1.0.63.617.g5aca9a2a
