### ISSUE TITLE
Play|Pause Problems

### ISSUE THREAD

**Issue by renatocfrancisco** [ShyykoSerhiy/vscode-spotify#175]
Most of the time, when i click the Play|Pause Button, it says **"Player command failed: Restriction violated - reason: UNKNOWN".** 
Or it says, please "Log In" in Spotify, even though, the player is open and already logged on. This is a problem with and without the Spotify Window opened.

![Code_8On1TUMlmE](https://user-images.githubusercontent.com/56325092/167159397-28e99a2e-b5ac-4bb8-b777-e32cddb7d9f1.png)

Aside this annoyance, i think vscode-spotify is cool. I wish there was a YT Music Extension ([it exists](https://github.com/sedders123/vscode-ytmusic)).

**Comment by invisi-splat** [comment]
I also have this problem - though I think it might be a rate-limit from Spotify if you try to pause/unpause too fast. Perhaps an internal timeout within the extension would fix this.

Here's a copyable version of the error message:
```
vscode-spotify: Failed to perform operation Unknown error: status code403 ; {
  "error" : {
    "status" : 403,
    "message" : "Player command failed: Restriction violated",
    "reason" : "UNKNOWN"
  }
}
```
