### ISSUE TITLE
Wrong stopped/playing state

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ShyykoSerhiy/vscode-spotify#2]
If I launch VSCode while Spotify was already playing it shows me the stop/play button as if the music was not playing (it shows play button):

![image](https://cloud.githubusercontent.com/assets/159209/11648184/09282c98-9d26-11e5-84dd-accf525e568c.png)

If I hit that play button, the music actually stops and it shows a stop icon:

![image](https://cloud.githubusercontent.com/assets/159209/11648193/1e5d2cc6-9d26-11e5-9164-6888524cf718.png)

It might be a small bug due to an assumption about the initial state of things.

**Comment by ShyykoSerhiy** [comment]
Published new version with some other goodies.
