### ISSUE TITLE
Is there a way to disable shortcuts?

### ISSUE THREAD

**Issue by pycckuu** [ShyykoSerhiy/vscode-spotify#24]
Hello, thanks for this great extension!

I was wondering if there is anyway to just disable shortcuts in your extension and keep vscode default ones?

Thank you

**Comment by ShyykoSerhiy** [comment]
sure. Here is how you can do it:
![recording](https://user-images.githubusercontent.com/1106995/31885073-472c9746-b7bd-11e7-8e45-0aa6b9318aee.gif)
