### ISSUE TITLE
Utilize the new Spotify Player API

### ISSUE THREAD

**Issue by Inclushe** [ShyykoSerhiy/vscode-spotify#27]
There's [new API endpoints in Spotify's API](https://beta.developer.spotify.com/documentation/web-api/reference/player/) which would give Windows users full compatibility with this extension, along with the ability to control the currently playing Spotify device.

**Comment by duttaditya18** [comment]
@Inclushe This is an awesome idea! We must start work on this immediately. 
@ShyykoSerhiy I will try to get comfortable with this project in a few days. I will make a PR doing what I can in the meanwhile.

**Comment by ShyykoSerhiy** [comment]
implementation began in [feat/web-api](/ShyykoSerhiy/vscode-spotify/tree/feat/web-api) branch

todo:
- [ ] refactor code to use redux as a state container (will make it simpler to work with increased complexity of web api implementation)
- [ ] write and deploy simple 'spotify auth server' with local (http://127.0.0.1:port or http://[::1]:port) loopback IP address
- [ ] implement auth in extension via 'spotify auth server'
- [ ] integrate web player api 
- [ ] implement song selection inside
- [ ] implement add to playlist
- [ ] implement like button (add to preferred playlist without the need of selection of actual playlist to add to)

**Comment by levrik** [comment]
Old API on Windows seems to be broken. At least it's not working for me anymore.

**Comment by levrik** [comment]
Just found spotify/web-api#492. We should keep an eye on that one. Apparently vscode-spotify began to work again. Not sure what was wrong before.

**Comment by LukasPolak** [comment]
When will be available full compatibility for Windows users?

**Comment by vmcbaptista** [comment]
What about the new Web Playback SDK? Maybe it avoids the need to create a local server and maybe we don't need that pooling mechanisms.
Have you check it already? 
https://developer.spotify.com/documentation/web-playback-sdk/

**Comment by ShyykoSerhiy** [comment]
@vmcbaptista nice catch. I'll have a look.

**Comment by ShyykoSerhiy** [comment]
implemented in 3.0.0
