### ISSUE TITLE
Show album title

### ISSUE THREAD

**Issue by mrcasals** [ShyykoSerhiy/vscode-spotify#28]
Hi!

First of all, thanks for your work on this extension, it's very handy! 

Is there any way to show the album title next to the track title? Something like `Artist name - Track name - Album name` would work for me.

I don't know much about how VSCode extensions work, soI can't help much, but if you don't have time to work on this I might be able to pull something off if you give me some hints on where to start 😄 

Thanks!

**Comment by ShyykoSerhiy** [comment]
That's should be quite easy to do. 
You need to add new field album: string to interface https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/src/SpotifyStatus.ts#L5. 

Then fix https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/src/spotify/OsAgnosticSpotifyClient.ts#L51 and https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/src/spotify/OsxSpotifyClient.ts#L69(this one will probably work already as it has the album field inside)

And at last fix https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/src/SpotifyStatus.ts#L71.

It would be great to expose https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/src/SpotifyStatus.ts#L71 as some kind of template string inside https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/package.json#L273 so everyone could change the "track title" the way they want.

**Comment by ShyykoSerhiy** [comment]
If you want you can give it a try.

**Comment by mrcasals** [comment]
@ShyykoSerhiy thanks for the hints! I've opened #29, which should close this issue. The PR adds the album name, and lets user configure how should the track info be displayed via settings.

Hope it's good enough!

**Comment by mrcasals** [comment]
Hi @ShyykoSerhiy! When are you going to release a new version with these changes? Do you have any
 planned date? 😄 

Thanks!

**Comment by ShyykoSerhiy** [comment]
Released as 2.3.0. Thx!

**Comment by mrcasals** [comment]
Awesome, thank you! :smile:
