### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by sgript** [ShyykoSerhiy/vscode-spotify#32]
Nothing appears after installation. VSC 1.21.0 on macOS 10.13.3.

**Comment by ShyykoSerhiy** [comment]
Do you have your spotify open?

**Comment by ShyykoSerhiy** [comment]
Can you please try setting "spotify.useCombinedApproachOnMacOS": true param to false?
<img width="954" alt="screen shot 2018-03-12 at 2 12 44 pm" src="https://user-images.githubusercontent.com/1106995/37301631-7d3650a6-25ff-11e8-9331-9a4250f609f5.png">

**Comment by ShyykoSerhiy** [comment]
You may have the same problem as in https://github.com/ShyykoSerhiy/vscode-spotify/issues/13 if you have some kind of corporate proxy or vpn

**Comment by sgript** [comment]
@ShyykoSerhiy settings `"spotify.useCombinedApproachOnMacOS": true` in settings did the trick, thank you!
