### ISSUE TITLE
Installed vscode-spotify extension but not working 

### ISSUE THREAD

**Issue by dreamwhite** [ShyykoSerhiy/vscode-spotify#43]
Just installed vscode-spotify extension with: 

`ext install shyykoserhiy.vscode-spotify`

Relaunched VSCode and the bar is not showing up. Spotify Desktop Client is running but there are no controls in VSCODE. Ubuntu 18.04 

EDIT:

Just closed VSCode and Spotify, launched first Spotify and after VSCode. The bar is still missing

**Comment by cajuuh** [comment]
check https://github.com/ShyykoSerhiy/vscode-spotify/issues/42

**Comment by ShyykoSerhiy** [comment]
fixed in 3.0.0
