### ISSUE TITLE
Plugin breaks my entire vscode setup

### ISSUE THREAD

**Issue by derouck** [ShyykoSerhiy/vscode-spotify#44]
Since the last update the plugin breaks all my vscode plugins.

Even the git builtin plugin is not working anymore when the plugin is enabled. Took me some time to figure it out. I guess it's caused by the last update?

Let me know if you need some more info.

**Comment by npasparuhov** [comment]
Same situation here, i have 20 extensions installed without any problem, when i install this vscode-spotify it breaks all other plugins, nothing is accessible and shown.

OS: macOS HighSierra 10.13.6
VS code: 1.25.1

Plugins that i have installed:
- Beautify
- Debugger for Chrome
- DotENV
- EditorConfig for VS Code
- ESLint
- Git History Diff
- GitLens
- IntelliSense for CSS class names in HTML
- JavaScript (ES6) code snippets
- JS-CSS-HTML Formatter
- Lodash
- npm
- npm Intellisense
- MagicPython
- Python
- React/Redux/react-router Snippets
- seti-icons
- Typescript React code snippets
- VS Live Share
- XML Tools

**Comment by derouck** [comment]
@ShyykoSerhiy Exactly some os/vscode config as @npasparuhov

**Comment by douglascamata** [comment]
I also have the problem, running macOS 10.13.6  and VSCode 1.26. If I enable this extension it crashes everything. Disabling it brings everything back. Didn't find any useful information in the logs.

**Comment by kyleboe** [comment]
Same situation as @npasparuhov and @douglascamata 
- OS: macOS 10.13.6 (17G65)
- VS code: 1.26.1 (1.26.1)

**Comment by douglascamata** [comment]
Stopped happening for me after the VSCode 1.26.1 update.

**Comment by ShyykoSerhiy** [comment]
should be fixed in 2.6.1
