### ISSUE TITLE
vscode-spotify: Failed to perform operation Unknown error: status code 403

### ISSUE THREAD

**Issue by mrtnpwn** [ShyykoSerhiy/vscode-spotify#55]
I just installed vscode-spotify and connected it to my Spotify account but it seems that I can't get it working, whenever I try to put a playlist it outputs this:

```
vscode-spotify: Failed to perform operation Unknown error: status code403 ; {
  "error" : {
    "status" : 403,
    "message" : "Not available for the current user"
  }
}
```

> Image
<img src="https://image.ibb.co/dsM8g9/vscode_spotify_error.png" alt="vscode_spotify_error" border="0">

*I'm using Linux, by the way...*

**Comment by mrtnpwn** [comment]
Dude, I'm using Spotify Premium.

**Comment by AdamTaxMan** [comment]
Have same problem on Windows 10 Spotify premium :(

**Comment by pgogousis** [comment]
Same problem here! Windows 10 - Premium Spotify & logged in but get

> vscode-spotify: You should be logged in order to use this feature.

**Comment by blackinitial** [comment]
whats??

**Comment by joaoalvaro** [comment]
How to login spotify on windows 10?

**Comment by champ96k** [comment]
> How to login to Spotify on Windows 10?

if you're using vscode then press

-> Ctrl + Shift + p
-> type spotify Sign In
-> press Enter

**Comment by TheWarrior047** [comment]
vscode-spotify: Failed to perform operation Unknown error: status code403 ; {
  "error" : {
    "status" : 403,
    "message" : "Player command failed: Premium required",
    "reason" : "PREMIUM_REQUIRED"
  }
}
