### ISSUE TITLE
Can't use tab with playlists and tracks

### ISSUE THREAD

**Issue by Prechan** [ShyykoSerhiy/vscode-spotify#57]
Hi,

I have a problem with the extension. I'm able to use shortcuts like play/next etc... at the bottom of vscode but when I open the tab, it's empty and a popin appear with this error code:

`vscode-spotify: You should be logged in order to use this feature.`

Did I miss something ? I'm on ubuntu with Spotify Desktop app running and a premium account. (edit: online mode on)
Thanks for you help and thanks you for this extension !

**Comment by ShyykoSerhiy** [comment]
Playlist/tracks feature uses Spotify Web Api. You need to sign in to use it (and you need to be a Spotify Premium uses. More on Premium here https://github.com/ShyykoSerhiy/vscode-spotify/issues/55#issuecomment-427707866) 
<img width="349" alt="signin" src="https://user-images.githubusercontent.com/1106995/46677414-9805ce00-cbb0-11e8-835a-7b79bd5a85bd.png">

**Comment by ShyykoSerhiy** [comment]
It should work fine for you. Feel free to reopen the issue if login button doesn't work for some reason.

**Comment by gityouser** [comment]
While in VS Code, hit "Command + P"(on Mac). From there type "> Spotify Sign In". 
This will make the connection with the Spotify API and send you on their website so you can login.
Voila!

**Comment by globantPipo** [comment]
Please refer to @gityouser Answer!  thanks buddy

**Comment by reaper8055** [comment]
> While in VS Code, hit "Command + P"(on Mac). From there type "> Spotify Sign In".
> This will make the connection with the Spotify API and send you on their website so you can login.
> Voila!

Command + Shift + P worked for me.

**Comment by kierancrowntrt** [comment]
I had to set Force Web API setting for this to work on OS X 10.15
