### ISSUE TITLE
How do you log in?

### ISSUE THREAD

**Issue by pzelnip** [ShyykoSerhiy/vscode-spotify#61]
When clicking the spotify icon in the explorer bar, I get: ```vscode-spotify: You should be logged in order to use this feature.```  Screenshot:

![screen shot 2018-10-10 at 10 17 11 am](https://user-images.githubusercontent.com/414933/46753836-bf729e80-cc75-11e8-881c-cf77cd94364a.png)

How do you log in?

VS Code: 1.28
Spotify Extension: 3.0.4
OS: OSX Sierra (10.12.6)

**Comment by ShyykoSerhiy** [comment]
see https://github.com/ShyykoSerhiy/vscode-spotify/issues/57#issuecomment-428222479

**Comment by vinujosef** [comment]
@ShyykoSerhiy Would it be good to add "Get vscode-spotify to work in VSCode" in documentation (since I and a couple of people still stumbled on this)?

**Comment by ShyykoSerhiy** [comment]
@vinujosef, there is a fix for this in 9412fac70ecff6d608fdb776bbe5d6ee62244b14 with the better message and sign in button right in the message itself. It should be released this weekend (would had been released previous on weekend if I didn't hit the wall with the https://github.com/spotify/web-api/issues/1297 issue.)
