### ISSUE TITLE
Cannot see current Song.

### ISSUE THREAD

**Issue by duttaditya18** [ShyykoSerhiy/vscode-spotify#63]
The current song playing is not visible after logging in. My VSCode Version is :

```
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

There is no User Setting for showing Current Song.

**Comment by ShyykoSerhiy** [comment]
Can you please check again?

**Comment by duttaditya18** [comment]
@ShyykoSerhiy Is there a user setting for showing / hiding the current song?

**Comment by ShyykoSerhiy** [comment]
No, there is no such user setting. Are you on Windows? If you are you need to sign in https://github.com/ShyykoSerhiy/vscode-spotify/issues/57#issuecomment-428222479

**Comment by duttaditya18** [comment]
Is there no way to know just the song that is playing without using the API? The API requires Spotify Premium. Is there any way to force it to use the older method that only displayed the Current Song playing?

 I am on Win10 : v10.0.17134 N/A Build 17134
VSCode is  v1.28.1

**Comment by ShyykoSerhiy** [comment]
Spotify removed local web server that allowed to get song title ~2 month ago. You should be able to login with free Spotify account, but the only thing that will work is displaying of the Current Song.

**Comment by duttaditya18** [comment]
@ShyykoSerhiy Displaying of the current song doesn't work for me either.

Is there any way you can implement it using : https://github.com/nadavbar/spotify-win-remote

**Comment by ShyykoSerhiy** [comment]
@duttaditya18 Are you sure that you've signed in? I've just created new free account, went to https://open.spotify.com/browse/featured, selected song, pressed play and it shows in vscode.

**Comment by ShyykoSerhiy** [comment]
And I've checked it on https://developer.spotify.com/console/get-user-player/ via "try it" feature. It works for my newly created free account.

**Comment by ShyykoSerhiy** [comment]
Maybe the api for free accounts it region dependant.

**Comment by duttaditya18** [comment]
@ShyykoSerhiy Okay. I am sorry for bothering you.

So Spotify is not available in my country. So, I use a VPN to sign in to the desktop app and then I can listen to music without needing any VPN. I just checked with a VPN active and the current song playing was showing.

Extremely sorry for being so stupid. Thanks for the help!
