### ISSUE TITLE
Icon order issue

### ISSUE THREAD

**Issue by icemouton** [ShyykoSerhiy/vscode-spotify#65]
For some reason the php debug extension inserts it's icon between some of your icons.
![image](https://user-images.githubusercontent.com/6319013/46889403-8c750a00-ce31-11e8-8647-c939d9fe090c.png)
As you can see it's between the play and song title icon ^

**Comment by ShyykoSerhiy** [comment]
see https://github.com/ShyykoSerhiy/vscode-spotify/issues/33#issuecomment-375766550 . Basically you need to change spotify.priorytyBase.
