### ISSUE TITLE
vscode-spotify: You should be logged in order to use this feature

### ISSUE THREAD

**Issue by mjspeck** [ShyykoSerhiy/vscode-spotify#68]
I get this message when clicking on the extension in VSCode. Also, all the 'tracks' and 'playlists' panes are blank.

<img width="1676" alt="screen shot 2018-10-17 at 10 07 48 pm" src="https://user-images.githubusercontent.com/20689127/47126986-2802e200-d259-11e8-874f-be813265c9ac.png">

You can see on the status bar that I am able to play music though, and I'm also logged in to Spotify.

**Comment by ShyykoSerhiy** [comment]
see https://github.com/ShyykoSerhiy/vscode-spotify/issues/57#issuecomment-428222479

**Comment by pgogousis** [comment]
Same issue here! Read the thread mentioned above but could not resolve it.

**Comment by gityouser** [comment]
While in VS Code, hit "Command + P"(on Mac). From there type "> Spotify Sign In". 
This will make the connection with the Spotify API and send you on their website so you can login.
Voila!

**Comment by Marmacanna** [comment]
Yeah It doesn't work for me, still getting an error. I tried to sign out and sign back in to see if that would work, but it won't sign me out. I've tried uninstalling the extension, then reinstalling. Same thing. Hmmm.

**Comment by thatbudakguy** [comment]
> While in VS Code, hit "Command + P"(on Mac).

to clarify, you want <kbd>⌘ command</kbd><kbd>shift</kbd><kbd>P</kbd> for the command palette, in case anybody else sees this.
