### ISSUE TITLE
Vscode spotify in sidebar expanding & getting focus whenever VS Code starts

### ISSUE THREAD

**Issue by pzelnip** [ShyykoSerhiy/vscode-spotify#78]
Every time I start VS Code, the sidebar expands and goes to the vscode-spotify bar.  Is there a way to disable that from happening?  If the sidebar was collapsed when I exit VSCode I'd like it to remain closed when I open it back up again.

Edit: workaround is to right-click on the sidebar and untick the vscode-spotify option.  This however disables vscode-spotify from the sidebar entirely.

VS Code Version: 1.29.1
vscode-spotify version: 3.1.0
OS: OSX 10.12.6 (Sierra)

**Comment by franck-noahk** [comment]
I found that even when you disable the vscode-spotify option it still pulls it up on the sidebar forcing it to appear until I click off of it.

**Comment by FOSSforlife** [comment]
I'm experiencing this as well on Linux, as of today. Didn't start happening until I signed in to Spotify. (For a while I was just using it for the keyboard shortcuts and didn't need to be logged in).

**Comment by AyhanSetirekli** [comment]
I'm seeing the same issue's - really annoying. I only tend to use the buttons on the bottom of the vscode screen. 

Wish they would fix this!

**Comment by visualcookie** [comment]
It's a real bummer in all honesty, that it always expands on opening a project. 😞

**Comment by Rikezenho** [comment]
It's reeeeeeally annoying!
Please guys, pay attention to this. Still happening :(

**Comment by ShyykoSerhiy** [comment]
@Rikezenho, I finally have some time to spare this weekend. Will fix it and hopefully release by the end of the week.

**Comment by ShyykoSerhiy** [comment]
Released in Released in 3.2.0
