### ISSUE TITLE
Error happening even running as administrator

### ISSUE THREAD

**Issue by maxdelemos** [ShyykoSerhiy/vscode-spotify#8]
When installing the extension the VSCode constantly shows the message below:

**Run VS Code with admin privileges so the changes can be applied.**

![spotify](https://cloud.githubusercontent.com/assets/6104188/16985167/2e34a3a0-4e55-11e6-8aa1-dc11411bbe65.png)

**Comment by ShyykoSerhiy** [comment]
Hi. The error message seems bizarre. You should not need admin privileges to install extension, however, judging by the look of VSCode window header you are running windows. The extension currently supports MacOS(Os X) only. It will change in the future with the issue https://github.com/ShyykoSerhiy/vscode-spotify/issues/7 resolved.

**Comment by ShyykoSerhiy** [comment]
Support of MacOS was implemented using https://developer.spotify.com/applescript-api/.
Unfortunately Spotify doesn't provide similar api for windows or linux. Windows and Linux implementations will use undocumented feature of spotify desktop client to operate in future(spotify creates local web server that exposes some of the needed functionality).

**Comment by maxdelemos** [comment]
Apologies, did not pay attention before installing **=**)

**Comment by maxdelemos** [comment]
so, today there is no way to develop an extension for Windows or Linux?

**Comment by ShyykoSerhiy** [comment]
There is a way :)
> Windows and Linux implementations will use undocumented feature of Spotify desktop client to operate in future(Spotify creates local web server that exposes some of the needed functionality).

**Comment by maxdelemos** [comment]
thank you

**Comment by ShyykoSerhiy** [comment]
@maxdelemos initial support for Windows is added in version 1.0.0.
