### ISSUE TITLE
Windows Login not working with postpaid spotify Premium

### ISSUE THREAD

**Issue by omkarubale** [ShyykoSerhiy/vscode-spotify#90]
vscode-spotify: Failed to perform operation Unknown error: status code403 ; { "error" : { "status" : 403, "message" : "Player command failed: Premium required", "reason" : "PREMIUM_REQUIRED" } }

This shows up in an error message box whenever I try to do anything with the Spotify extension. I just purchased Spotify Premium postpaid on an Indian account and I am trying to get it to work, but so far no success.

Please fix this ASAP. Thank you.

**Comment by kuem2405** [comment]
I have been this the error too

**Comment by karthikone** [comment]
Me too. . .

**Comment by rohangoyal-rg** [comment]
Me too

**Comment by Skolozub** [comment]
Me too...

**Comment by AkshayKumar007** [comment]
me too

**Comment by omkarubale** [comment]
Hi guys, I realised that the spotify app has to be opened before you can use the extension in VSCode.
Once the spotify app is opened, the extension starts working.

**Comment by Jaserto** [comment]
Me too, I open the spotify app before and after, but the problem is still.

**Comment by vishalsondarva** [comment]
Me too...
